sudo: required
services:
  - docker
language: generic
cache:
  timeout: 360
  directories:
  - "$HOME/.stack/"
  - "$HOME/.local/bin/"
  - ".stack-work/"
install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- stack install tasty-discover
jobs:
  include:
    - stage: build dependencies
      script: stack --no-terminal --install-ghc test --bench --only-dependencies
    - stage: run test
      script: stack --no-terminal test --bench --no-run-benchmarks --no-haddock-deps --pedantic
    - stage: push docker image
      if: branch = master AND type = push
      script:
      - stack docker pull
      - stack --docker image container
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker tag scrapbook $TRAVIS_REPO_SLUG
      - docker push $TRAVIS_REPO_SLUG
    - stage: push docker image
      if: type = tag
      script:
      - stack docker pull
      - stack --docker image container
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker tag scrapbook $TRAVIS_REPO_SLUG:$TRAVIS_TAG
      - docker push $TRAVIS_REPO_SLUG:$TRAVIS_TAG
