name:                scrapbook
version:             0.1.1
github:              "matsubara0507/scrapbook"
license:             MIT
author:              "MATSUBARA Nobutada"
copyright:           "2018 MATSUBARA Nobutada"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on Github at <https://github.com/matsubara0507/scrapbook#readme>

ghc-options:
- -Wall

dependencies:
- base >= 4.7 && < 5
- extensible
- extensible-instances
- lens
- text
- yaml

library:
  source-dirs: src
  dependencies:
  - containers
  - data-default
  - exceptions
  - feed
  - monad-logger
  - mtl
  - req
  - shelly
  - time
  - text-conversions
  - xml-conduit
  - xml-types
  other-modules:
  - ScrapBook.Feed.Atom.Internal
  - ScrapBook.Fetch.Internal
  - ScrapBook.Internal.Utils
  - ScrapBook.Write.Internal

executables:
  scrapbook:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gitrev
    - scrapbook

tests:
  scrapbook-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scrapbook
