name:                scrapbook
version:             0.1.2
github:              "matsubara0507/scrapbook"
license:             MIT
author:              "MATSUBARA Nobutada"
copyright:           "2018 MATSUBARA Nobutada"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on Github at <https://github.com/matsubara0507/scrapbook#readme>

ghc-options:
- -Wall

default-extensions:
- NoImplicitPrelude

dependencies:
- aeson
- aeson-pretty
- base >= 4.7 && < 5
- data-default
- data-default-instances-text
- exceptions
- extensible
- extensible-instances
- feed
- monad-logger
- mtl
- req
- rio
- shelly
- text-conversions
- unordered-containers
- xml-conduit
- xml-types
- yaml

library:
  source-dirs: src
  other-modules:
  - ScrapBook.Feed.Atom.Internal
  - ScrapBook.Fetch.Internal
  - ScrapBook.Internal.Utils
  - ScrapBook.Write.Internal

executables:
  scrapbook:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - drinkery
    - gitrev
    - scrapbook
    - text # rio is not support console I/O yet

tests:
  scrapbook-test:
    main:                Driver.hs
    source-dirs:
    - test
    - src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scrapbook
    - tasty
    - tasty-hunit
