name:                scrapbook
version:             0.6.0
synopsis:            collect posts of site that is wrote in config yaml using feed or scraping
github:              "matsubara0507/scrapbook"
license:             MIT
author:              "MATSUBARA Nobutada"
maintainer:          "MATSUBARA Nobutada"
copyright:           "2018 MATSUBARA Nobutada"
category:            Web

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/matsubara0507/scrapbook#readme>

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -optP-Wno-nonportable-include-path

default-extensions:
- NoImplicitPrelude

dependencies:
- base >= 4.7 && < 5
- extensible >= 0.5
- rio >= 0.1.5
- scrapbook-core >= 0.5
- yaml

library:
  source-dirs: src

executables:
  scrapbook:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - drinkery
    - githash
    - scrapbook

tests:
  scrapbook-test:
    main: Spec.hs
    source-dirs:
    - test
    - src
    dependencies:
    - scrapbook
    - tasty
    - tasty-hunit
