resolver: lts-12.26
packages:
- .
extra-deps:
- drinkery-0.4
- extensible-0.5

docker:
  repo: fpco/stack-build
  enable: false
image:
  container:
    name: scrapbook
    base: fpco/ubuntu-with-libgmp
