resolver: lts-12.26
packages:
- .
extra-deps:
- data-default-instances-text-0.0.1
- drinkery-0.4

docker:
  repo: fpco/stack-build
  enable: false
image:
  container:
    name: scrapbook
    base: fpco/ubuntu-with-libgmp
