name: Build Application

on:
  pull_request: null
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ghc: ["9.2.2"]

    steps:
    - uses: actions/checkout@v2

    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: "\
          ${{ runner.os }}-stack\
          -${{ hashFiles('**/stack.yaml.lock') }}\
          -${{ hashFiles('**/package.yaml') }}\
        "
        restore-keys: |
          ${{ runner.os }}-stack-
    - uses: haskell/actions/setup@v2
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: 'latest'

    - name: Install dependencies
      run: stack --system-ghc test --only-dependencies

    - name: Build and Test
      run: stack --system-ghc test --copy-bins --local-bin-path=./bin
